### PR TITLE
Add navigation bar and incorporate TailwindCSS

### LINKED ISSUE #10: Build a navigation bar for the application

### LINKED ISSUE #25: Implement styling in Tailwind CSS [Update existing PRs]
## Issue Description

- Currently, styles are implemented using vanilla CSS incorporated within the TSX files using [`styled-components`](https://styled-components.com/).
- In order to style components, we can use [TailwindCSS](https://tailwindcss.com/). Thus, we need to transition from `styled-components` to TailwindCSS.

## Steps to Resolve

1. In order to install TailwindCSS in our CRA app, follow the guide here: https://tailwindcss.com/docs/guides/create-react-app
2. Transition the styles following the Core Concepts of TailwindCSS: https://tailwindcss.com/docs/utility-first
3. Eliminate all usage of `styled-components`

### PR DESCRIPTION
**Pull request by AVS1508**
This PR fixes #10 and fixes #25.

## Views
screencapture-localhost-3000-2023-01-28-22_26_11

### CODE REVIEW

**Comment by sahilgupta17** [comment]
I think the SideBar is not collapsible at this moment. Could you add the following changes?

1. Make Sidebar collapsible as well
2. Add react icons for the menu items
3. Dark mode toggle button(can use sun and moon icon to toggle between theme)
4. Convert the current app from JavaScript to TypeScript

Reference to collapsible sidebar from react pro sidebar documentation
Screenshot 2023-01-30 at 5 50 00 PM

**Comment by AVS1508** [comment]
Made the necessary changes to convert the repository to use TSX for React

**Comment by AVS1508** [comment]
### Changelog ###

- Made Sidebar collapsible
- Added icons (FontAwesome) for Menu items

### Pending ###

- Implement theming and dark mode trigger

**Comment by AVS1508** [comment]
Should do dark mode theming in another PR

**Comment by AVS1508** [comment]
Ready to review @sahilgupta17 @kiratarora

**Comment by AVS1508** [comment]
TODO: Remove the Members submenu; you only need a direct link to Members

**Comment by AVS1508** [comment]
This PR is ready for review! @sahilgupta17 @kiratarora kindly review as soon as possible.

**Comment by AVS1508** [comment]
This PR is ready for review for solving both #10 and #25! @sahilgupta17 @mstuteja @kiratarora kindly review as soon as possible.

**Review by kiratarora — APPROVED** [review]
LGTM!

**Pull request merged**
